server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    s3:
      secret:
        key: "+4iXz3+91IbWF6OLZRgz7qkvAPGofBwC56Ww06bL"
      access:
        key: "AKIAZMUWQLW5L77GYI7J"